--Vistas para los reportes

--PRIMER VISTA

CREATE VIEW MayorMenorVenta AS

SELECT MAX(TOTAL) AS MAYORVENTA, MIN(TOTAL) AS MENORVENTA FROM DETALLE_VENTA;

--SEGUNDA VISTA

CREATE VIEW MayorMenorCompra AS

SELECT MAX(SUBTOTAL) AS MAYORCOMPRA, MIN(SUBTOTAL) AS MENORCOMPRA FROM COMPRA;

--TERCER VISTA

CREATE VIEW PrimerUltimaCompra AS

SELECT MAX(FECHA) AS ULTIMACOMPRA, MIN(FECHA) AS PRIMERACOMPRA FROM COMPRA;

--CUARTA VISTA

CREATE VIEW VentasTotales AS

SELECT COUNT(*) AS TOTALFILAS, SUM(TOTAL) AS VENTASTOTALES FROM VENTA;

--QUINTA VISTA

CREATE VIEW VentasMenorMil AS

SELECT * FROM VENTA WHERE TOTAL <'1000';

--SEXTA VISTA

CREATE VIEW CERVEZAS AS 

SELECT * FROM BEBIDAS WHERE TIPO_BEBIDA = 'CERVEZA';

--SEPTIMA VISTA

CREATE VIEW REFRESCOS AS 

SELECT * FROM BEBIDAS WHERE TIPO_BEBIDA = 'REFRESCO';

--OCTAVA VISTA

CREATE VIEW TotalProveedores AS 

SELECT COUNT(*) AS TOTALDEPROVEDORES FROM PROVEEDORES;

--NOVENA VISTA

CREATE VIEW CLIENTEmenorOigual1500 AS

SELECT ID_CLIENTE FROM VENTA WHERE TOTAL <= '1500' GROUP BY ID_CLIENTE;

--DECIMA VISTA

CREATE VIEW ProductoMASyMENOScaro AS

SELECT MAX(PRECIO_COSTO) AS PRODUCTOMASCARO, MIN(PRECIO_COSTO) AS PRODUCTOMASBARATO FROM DETALLE_COMPRA;



